// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {settings} from '../models';
import {git} from '../models';

export function Commit(arg1:string):Promise<void>;

export function Diff(arg1:string,arg2:boolean,arg3:boolean):Promise<main.DiffResult>;

export function Discard(arg1:string,arg2:boolean):Promise<void>;

export function GetSettings():Promise<settings.Settings>;

export function Info():Promise<main.RepoInfo>;

export function Redo():Promise<string>;

export function Stage(arg1:string):Promise<void>;

export function StageAll():Promise<void>;

export function StageLines(arg1:string,arg2:Array<git.PatchHunk>):Promise<void>;

export function Status():Promise<Array<git.FileStatus>>;

export function Undo():Promise<string>;

export function UndoState():Promise<main.UndoState>;

export function Unstage(arg1:string):Promise<void>;

export function UnstageAll():Promise<void>;

export function UnstageLines(arg1:string,arg2:Array<git.PatchHunk>):Promise<void>;

export function UpdateSettings(arg1:settings.Settings):Promise<settings.Settings>;
