// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Commit(arg1) {
  return window['go']['main']['App']['Commit'](arg1);
}

export function Diff(arg1, arg2, arg3) {
  return window['go']['main']['App']['Diff'](arg1, arg2, arg3);
}

export function Discard(arg1, arg2) {
  return window['go']['main']['App']['Discard'](arg1, arg2);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function Info() {
  return window['go']['main']['App']['Info']();
}

export function Redo() {
  return window['go']['main']['App']['Redo']();
}

export function Stage(arg1) {
  return window['go']['main']['App']['Stage'](arg1);
}

export function StageAll() {
  return window['go']['main']['App']['StageAll']();
}

export function StageLines(arg1, arg2) {
  return window['go']['main']['App']['StageLines'](arg1, arg2);
}

export function Status() {
  return window['go']['main']['App']['Status']();
}

export function Undo() {
  return window['go']['main']['App']['Undo']();
}

export function UndoState() {
  return window['go']['main']['App']['UndoState']();
}

export function Unstage(arg1) {
  return window['go']['main']['App']['Unstage'](arg1);
}

export function UnstageAll() {
  return window['go']['main']['App']['UnstageAll']();
}

export function UnstageLines(arg1, arg2) {
  return window['go']['main']['App']['UnstageLines'](arg1, arg2);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
